[tools]
age = "latest"
bat = "latest"
crush = "latest"
fzf = "latest"
go = "latest"
jq = "latest"
kind = "latest"
kubectl = "latest"
kubectx = "latest"
neovim = "latest"
node = "latest"
python = "latest"
rclone = "latest"
restic = "latest"
rust = "latest"
rustic = "latest"
starship = "latest"
uv = "latest"
yq = "latest"

[settings]
experimental = true
install_before = "7d"
