# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$username\
$hostname\
$kubernetes\
$python\
$directory\
$line_break\
$time\
$status\
$character"""

[time]
disabled = false
time_format = "%H:%M"

[kubernetes]
format = '''[k8s:\(](blue bold)[$context](red bold)[/](blue bold)[$namespace](green bold)[\)](blue bold) '''
disabled = false

[python]
disabled = false
